domain: dqlite.io

image: prod-comms.ps5.docker-registry.canonical.com/dqlite.io

env:
  - name: SENTRY_DSN
    value: https://426397ba83be483a8a8d1ed92b0f0623@sentry.is.canonical.com//17
    
  - name: FLASK_GOOGLE_SEARCH_API_KEY
    secretKeyRef:
      key: google-custom-search-key
      name: google-api

  - name: FLASK_SECRET_KEY
    secretKeyRef:
      key: dqlite-io
      name: secret-keys
      
# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'dqlite.io' ) {
      rewrite ^ https://dqlite.io$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
