name: PR checks
on: pull_request

env:
  FLASK_SECRET_KEY: insecure_test_key
  SECRET_KEY: insecure_test_key
  FLASK_GOOGLE_SEARCH_API_KEY: insecure_test_key
jobs:
  run-dotrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dotrun
        run: sudo pip3 install dotrun requests==2.31.0 # requests version is pinned to avoid breaking changes, can be removed once issue is resolved: https://github.com/docker/docker-py/issues/3256

      - name: Install dependencies
        run: |
          sudo chmod -R 777 .
          dotrun install

      - name: Build assets
        run: dotrun build

      - name: Test site
        run: dotrun & curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:8037

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo pip3 install flake8 black

      - name: Lint python
        run: yarn lint-python

  lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss

  test-python:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Install dependencies
        run: sudo pip3 install coverage

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Build resources
        run: yarn build

      - name: Run tests with coverage
        run: |
          coverage run  --source=. -m unittest discover tests
          bash <(curl -s https://codecov.io/bash) -cF python

  inclusive-naming-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check inclusive naming
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail-on-error: true
